import os

DHR_CATALOG_ROOT: str = os.getenv("DHR_CATALOG_ROOT")
CDSE_CATALOG_ROOT: str = os.getenv("CDSE_CATALOG_ROOT")

BACKEND_OUTPUT_DIRECTORY: str = os.getenv("BACKEND_OUTPUT_DIRECTORY")
FRONTEND_OUTPUT_DIRECTORY: str = os.getenv("FRONTEND_OUTPUT_DIRECTORY")
