version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    container_name: "backend_container"
    env_file:
      - .env
    ports:
      - "8081:8081"
    volumes:
      - tmp:/tmp
      - shared_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    restart: always
    container_name: "frontend_container"
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - shared_data:/usr/local/apache2/htdocs/data
      - ./certbot-www:/usr/local/apache2/htdocs/certbot
      - ./certs:/etc/letsencrypt
    depends_on:
      - backend

  gjtiff:
    build: ./gjtiff
    container_name: "gjtiff_container"
    command: ["sleep", "infinity"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - tmp:/tmp
      - shared_data:/data

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot-www:/var/www/certbot
      - ./certs:/etc/letsencrypt
    entrypoint: sh -c "sleep infinity"

  mongo:
    image: mongo
    container_name: "mongodb_container"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO__USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO__PASSWORD}
#    volumes:
#      - mongodb_data:/data/db

volumes:
  shared_data:
  tmp:
#  mongodb_data:
