version: '3.8'

services:
  backend:
    build: ./backend
    container_name: "backend_container"
    env_file:
      - variables.env
    ports:
      - "8081:8081"
    volumes:
      - tmp:/tmp
      - shared_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build: ./frontend
    container_name: "frontend_container"
    env_file:
      - variables.env
    ports:
      - "8080:8080"
    volumes:
      - shared_data:/usr/local/apache2/htdocs/data
    depends_on:
      - backend

  gjtiff:
    build: ./gjtiff
    container_name: "gjtiff_container"
    command: ["sleep", "infinity"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - tmp:/tmp
      - shared_data:/data

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot-www:/var/www/certbot
      - ./certs:/etc/letsencrypt
    entrypoint: sh -c "sleep infinity"

volumes:
  shared_data:
  tmp:
