version: '3.8'

services:
  backend:
    build: ./backend
    image: oculus/backend:latest
    restart: always
    container_name: "oculus_backend"
    env_file:
      - .env
    ports:
      - "8081:8081"
    volumes:
      - tmp:/tmp
      - shared_data:/data
    depends_on:
      - mongo
      - redis

  celery:
    build: ./backend
    image: oculus/backend:latest
    entrypoint: celery
    command: -A celery_app.celery_app worker -l info -E
    container_name: "oculus_celery"
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
    volumes:
      - shared_data:/data
      - tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis:alpine
    container_name: "oculus_redis"
#    ports:
#      - "6379:6379"

  mongo:
    image: mongo
    container_name: "oculus_mongodb"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO__USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO__PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO__DB}
#    volumes:
#      - mongodb_data:/data/db

  frontend:
    build: ./frontend
    restart: always
    container_name: "oculus_frontend"
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - shared_data:/usr/local/apache2/htdocs/data
      - certbot_challenge:/usr/local/apache2/htdocs/.well-known/acme-challenge
      - ./certs:/etc/letsencrypt
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    container_name: oculus_certbot
    restart: always
    volumes:
      - certbot_challenge:/var/www/certbot
      - ./certs:/etc/letsencrypt
      - ./frontend/run_certbot.sh:/run_certbot.sh
    env_file:
      - .env
    #entrypoint: sh -c "sleep infinity"
    entrypoint: sh /run_certbot.sh

  gjtiff:
    build: ./gjtiff
    container_name: "oculus_gjtiff"
    command: ["sleep", "infinity"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - tmp:/tmp
      - shared_data:/data

volumes:
  certbot_challenge:
  shared_data:
  tmp:
#  mongodb_data:
