version: '3.8'

services:
  backend:
    build: ./backend
    image: oculus/backend:latest
    restart: always
    container_name: "oculus_backend"
    env_file:
      - .env
    ports:
      - "8081:8081"
    volumes:
      - tmp:/tmp
      - shared_data:/data
    depends_on:
      - mongo
      - redis
    labels:
      - "app=oculus"
      - "component=backend"
    logging:
      driver: "journald"
      options:
        tag: "oculus"
        labels: "app,component"

  celery:
    build: ./backend
    image: oculus/backend:latest
    entrypoint: celery
    command: -A celery_app.celery_app worker -l info -E
    container_name: "oculus_celery"
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
    volumes:
      - shared_data:/data
      - tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "app=oculus"
      - "component=celery"
    logging:
      driver: "journald"
      options:
        tag: "oculus"
        labels: "app,component"

  redis:
    image: redis:alpine
    container_name: "oculus_redis"
    labels:
      - "app=oculus"
      - "component=redis"
    logging:
      driver: "journald"
      options:
        tag: "oculus"
        labels: "app,component"

  mongo:
    image: mongo
    container_name: "oculus_mongodb"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
#    volumes:
#      - mongodb_data:/data/db
    labels:
      - "app=oculus"
      - "component=mongo"
    logging:
      driver: "journald"
      options:
        tag: "oculus"
        labels: "app,component"

  frontend:
    build: ./frontend
    restart: always
    container_name: "oculus_frontend"
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - shared_data:/usr/local/apache2/htdocs/data
      - certbot_challenge:/usr/local/apache2/htdocs/challenge #/.well-known/acme-challenge
      - ./certs:/etc/letsencrypt
    depends_on:
      - backend
    labels:
      - "app=oculus"
      - "component=frontend"
    logging:
      driver: "journald"
      options:
        tag: "oculus"
        labels: "app,component"

  certbot:
    image: certbot/certbot
    container_name: oculus_certbot
    restart: always
    volumes:
      - certbot_challenge:/var/www/certbot
      - ./certs:/etc/letsencrypt
      - ./frontend/run_certbot.sh:/run_certbot.sh
    env_file:
      - .env
    entrypoint: sh /run_certbot.sh

  gjtiff:
    build: ./gjtiff
    container_name: "oculus_gjtiff"
    command: ["sleep", "infinity"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - tmp:/tmp
      - shared_data:/data
    labels:
      - "app=oculus"
      - "component=gjitff"
    logging:
      driver: "journald"
      options:
        tag: "oculus"
        labels: "app,component"

volumes:
  certbot_challenge:
  shared_data:
  tmp:
#  mongodb_data:
